version: '3.2'

services:
  copaco-node:
    container_name: copaco-node
    build:
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=production
    volumes:
      - .:/usr/src/app
